import React, { createContext, useContext, useState } from "react";

const AppContext = createContext();

export const AppProvider = ({ children }) => {
  // ✅ Current User (can be changed via role switch)
  const [currentUserRole, setCurrentUserRole] = useState("HR Manager");

  const currentUser = {
    id: "EMP002",
    name: "Bob HR",
    email: "bob.hr@company.com",
    role: currentUserRole,
    avatar: "https://ui-avatars.com/api/?name=Bob+HR&background=0D8ABC&color=fff",
  };

  // ✅ Mock Employees
  const mockEmployees = {
    EMP001: { id: "EMP001", name: "Alice HR", role: "HR Manager", email: "alice@company.com" },
    EMP002: { id: "EMP002", name: "Bob HR", role: "Recruiter", email: "bob@company.com" },
    EMP003: { id: "EMP003", name: "Sonia Sharma", role: "Hiring Manager", email: "sonia@company.com" },
    EMP004: { id: "EMP004", name: "Michael Brown", role: "Hiring Manager", email: "michael@company.com" },
    EMP005: { id: "EMP005", name: "Sarah Johnson", role: "Hiring Manager", email: "sarah@company.com" },
  };

  // ✅ Mock MRFs with ALL required fields for ManageMrf page
  const [mockMrfs, setMockMrfs] = useState([
    {
      id: "MRF101",
      designation: "Frontend Developer",
      department: "Engineering",
      location: "Bangalore",
      expMin: 2,
      expMax: 5,
      status: "Open",
      priority: "High",
      postingDate: "2025-10-15",
      fulfillBy: "2025-12-20",  // ✅ Required for ManageMrf
      hiringManager: "Sonia Sharma",  // ✅ Required for ManageMrf
      hiringManagerId: "EMP003",
      skills: ["React", "JavaScript", "CSS", "HTML"],
      assignedTo: "EMP002",  // ✅ Must match currentUser.id for filtering
      requirementType: "Expansion",
      employmentType: "Full-time",
      workMode: "Hybrid",
      positions: 3,
      budgetApproved: true,
      salaryRange: "₹8-15 LPA",
      jobDescription: "We are looking for skilled frontend developers to build modern web applications using React and related technologies.",
      educationQualification: "B.Tech/MCA in Computer Science",
      rounds: [  // ✅ Interview rounds for "Manage Rounds" feature
        {
          roundNo: 1,
          name: "Screening Call",
          interviewer: "Bob HR",
          mode: "Phone",
          date: "2025-11-18",
          time: "10:00",
          notes: "Initial screening - 15 minutes"
        },
        {
          roundNo: 2,
          name: "Technical Round",
          interviewer: "Sonia Sharma",
          mode: "Video",
          date: "2025-11-20",
          time: "14:00",
          notes: "Technical assessment - 60 minutes"
        }
      ],
      publishedOn: ["LinkedIn", "Indeed", "Naukri"],
      postings: [  // ✅ Required for ManageCandidates page
        {
          website: "LinkedIn",
          url: "https://linkedin.com/jobs/frontend-dev",
          views: 450,
          postedBy: "Alice HR",
          datePosted: "2025-10-16",
        },
        {
          website: "Indeed",
          url: "https://indeed.com/job/frontend-dev",
          views: 230,
          postedBy: "Alice HR",
          datePosted: "2025-10-17",
        },
        {
          website: "Naukri",
          url: "https://naukri.com/frontend-developer",
          views: 180,
          postedBy: "Bob HR",
          datePosted: "2025-10-18",
        },
      ],
    },
    {
      id: "MRF102",
      designation: "Backend Developer",
      department: "Engineering",
      location: "Hyderabad",
      expMin: 3,
      expMax: 6,
      status: "Open",
      priority: "Medium",
      postingDate: "2025-10-12",
      fulfillBy: "2025-12-10",
      hiringManager: "Sonia Sharma",
      hiringManagerId: "EMP003",
      skills: ["Node.js", "MongoDB", "Express", "REST APIs"],
      assignedTo: "EMP002",
      requirementType: "Replacement",
      employmentType: "Full-time",
      workMode: "Remote",
      positions: 2,
      budgetApproved: true,
      salaryRange: "₹10-18 LPA",
      jobDescription: "Backend developer role focusing on Node.js microservices and database design.",
      educationQualification: "B.Tech/MCA in Computer Science",
      rounds: [
        {
          roundNo: 1,
          name: "HR Screening",
          interviewer: "Bob HR",
          mode: "Phone",
          date: "2025-11-17",
          time: "11:00",
          notes: "Background verification and availability check"
        }
      ],
      publishedOn: ["LinkedIn", "Indeed"],
      postings: [
        {
          website: "LinkedIn",
          url: "https://linkedin.com/jobs/backend-dev",
          views: 350,
          postedBy: "Bob HR",
          datePosted: "2025-10-13",
        },
        {
          website: "Indeed",
          url: "https://indeed.com/job/backend-dev",
          views: 200,
          postedBy: "Bob HR",
          datePosted: "2025-10-14",
        },
      ],
    },
    {
      id: "MRF103",
      designation: "DevOps Engineer",
      department: "Engineering",
      location: "Pune",
      expMin: 4,
      expMax: 7,
      status: "Open",
      priority: "High",
      postingDate: "2025-11-01",
      fulfillBy: "2025-12-30",
      hiringManager: "Sarah Johnson",
      hiringManagerId: "EMP005",
      skills: ["AWS", "Docker", "Kubernetes", "Jenkins", "CI/CD"],
      assignedTo: "EMP002",
      requirementType: "Expansion",
      employmentType: "Full-time",
      workMode: "Hybrid",
      positions: 2,
      budgetApproved: true,
      salaryRange: "₹15-25 LPA",
      jobDescription: "Looking for DevOps engineers to manage cloud infrastructure and deployment pipelines.",
      educationQualification: "B.Tech in Computer Science or related",
      rounds: [],
      publishedOn: ["LinkedIn", "Naukri"],
      postings: [
        {
          website: "LinkedIn",
          url: "https://linkedin.com/jobs/devops-engineer",
          views: 280,
          postedBy: "Bob HR",
          datePosted: "2025-11-02",
        },
        {
          website: "Naukri",
          url: "https://naukri.com/devops-engineer",
          views: 150,
          postedBy: "Bob HR",
          datePosted: "2025-11-03",
        },
      ],
    },
    {
      id: "MRF104",
      designation: "Product Manager",
      department: "Product",
      location: "Mumbai",
      expMin: 5,
      expMax: 8,
      status: "Open",
      priority: "Critical",
      postingDate: "2025-10-05",
      fulfillBy: "2025-11-30",
      hiringManager: "Michael Brown",
      hiringManagerId: "EMP004",
      skills: ["Product Strategy", "Roadmap Planning", "User Research", "Agile"],
      assignedTo: "EMP002",
      requirementType: "New Position",
      employmentType: "Full-time",
      workMode: "In-Office",
      positions: 1,
      budgetApproved: true,
      salaryRange: "₹20-30 LPA",
      jobDescription: "Experienced product manager to lead product development and strategy.",
      educationQualification: "MBA or B.Tech with relevant experience",
      rounds: [
        {
          roundNo: 1,
          name: "Initial Discussion",
          interviewer: "Michael Brown",
          mode: "Video",
          date: "2025-11-16",
          time: "15:00",
          notes: "Product thinking and case study discussion"
        }
      ],
      publishedOn: ["LinkedIn"],
      postings: [
        {
          website: "LinkedIn",
          url: "https://linkedin.com/jobs/product-manager",
          views: 520,
          postedBy: "Alice HR",
          datePosted: "2025-10-06",
        },
      ],
    },
  ]);

  // ✅ Mock Candidates with ALL required fields for all three pages
  const [mockCandidates, setMockCandidates] = useState([
    // ========== Candidates for MRF101 - Frontend Developer ==========
    {
      id: "CAND001",
      mrfId: "MRF101",
      name: "Rahul Mehta",
      email: "rahul.mehta@gmail.com",
      contactNumber: "+91-9876543210",
      experience: 3,
      expectedSalary: 8,
      currentSalary: 6,
      noticePeriod: "30 days",
      designation: "Frontend Engineer",
      qualification: "B.Tech in Computer Science",
      languages: ["English", "Hindi"],
      source: "LinkedIn",

      // ✅ For ManageMrf KPI calculations
      status: "Shortlisted",
      appliedDate: "2025-11-10",
      createdAt: "2025-11-10",
      pitchCallCompleted: true,
      assessmentCompleted: false,
      interviewCompleted: false,
      offerSent: false,

      // ✅ For ManageCandidates page
      inviteStatus: "Interested",
      sentToHiringManager: false,
      hmReviewStatus: "Pending",
      currentStage: 1,
      shortlisted: true,
      remark: "Strong React skills, good cultural fit",
      isActive: true,

      // ✅ For CandidateDetails page - Pitch Call
      pitchCallStatus: "Completed",
      pitchCallRemarks: "Candidate showed strong interest. Good communication skills.",
      pitchCallDate: "2025-11-12",
      pitchCallTime: "10:00",
      pitchTrackerUpdated: true,

      // ✅ For CandidateDetails page - Assessment
      assessmentDate: "",
      assessmentType: "",
      assessmentMode: "",
      assessmentDateTime: "",
      assessmentStatus: "",
      assessmentRemarks: "",

      // ✅ For CandidateDetails page - Interview
      interviewDate: "",
      interviewDateTime: "",
      interviewer1Name: "",
      interviewer2Name: "",
      interviewStatus: "",
      interviewRemarks: "",

      // ✅ For CandidateDetails page - Offer
      offerDate: "",
      offerAmount: "",
      joiningDate: "",
      offerStatus: "",
      offerRemarks: "",

      // Additional fields
      age: 26,
      gender: "Male",
      skills: ["React", "JavaScript", "CSS", "HTML"],
      preferredCallTime: "10:00 AM - 12:00 PM",
      callOption: "Phone",
      dateApplied: "2025-11-10",
    },
    {
      id: "CAND002",
      mrfId: "MRF101",
      name: "Ananya Verma",
      email: "ananya.verma@gmail.com",
      contactNumber: "+91-9876543211",
      experience: 2,
      expectedSalary: 6,
      currentSalary: 4.5,
      noticePeriod: "60 days",
      designation: "React Developer",
      qualification: "BCA",
      languages: ["English"],
      source: "Indeed",

      status: "Assessment",
      appliedDate: "2025-11-12",
      createdAt: "2025-11-12",
      pitchCallCompleted: true,
      assessmentCompleted: false,
      interviewCompleted: false,
      offerSent: false,

      inviteStatus: "Interested",
      sentToHiringManager: false,
      hmReviewStatus: "Pending",
      currentStage: 2,
      shortlisted: true,
      remark: "Junior developer with potential",
      isActive: true,

      pitchCallStatus: "Completed",
      pitchCallRemarks: "Enthusiastic candidate, needs more experience",
      pitchCallDate: "2025-11-13",
      pitchCallTime: "14:00",
      pitchTrackerUpdated: true,

      assessmentDate: "2025-11-18",
      assessmentType: "Technical",
      assessmentMode: "Online",
      assessmentDateTime: "2025-11-18T10:00",
      assessmentStatus: "Scheduled",
      assessmentRemarks: "",

      interviewDate: "",
      interviewDateTime: "",
      interviewer1Name: "",
      interviewer2Name: "",
      interviewStatus: "",
      interviewRemarks: "",

      offerDate: "",
      offerAmount: "",
      joiningDate: "",
      offerStatus: "",
      offerRemarks: "",

      age: 24,
      gender: "Female",
      skills: ["React", "JavaScript", "CSS"],
      preferredCallTime: "2:00 PM - 4:00 PM",
      callOption: "Video",
      dateApplied: "2025-11-12",
    },
    {
      id: "CAND003",
      mrfId: "MRF101",
      name: "Ravi Kumar",
      email: "ravi.kumar@gmail.com",
      contactNumber: "+91-9876543212",
      experience: 4,
      expectedSalary: 9,
      currentSalary: 7,
      noticePeriod: "45 days",
      designation: "Frontend Developer",
      qualification: "MCA",
      languages: ["English", "Kannada"],
      source: "Naukri",

      status: "Rejected",
      appliedDate: "2025-11-08",
      createdAt: "2025-11-08",
      pitchCallCompleted: true,
      assessmentCompleted: false,
      interviewCompleted: false,
      offerSent: false,

      inviteStatus: "Not Interested",
      sentToHiringManager: false,
      hmReviewStatus: "Rejected",
      currentStage: 0,
      shortlisted: false,
      remark: "Not interested in hybrid work model",
      isActive: false,

      pitchCallStatus: "Rejected",
      pitchCallRemarks: "Candidate declined due to work location preference",
      pitchCallDate: "2025-11-09",
      pitchCallTime: "11:00",
      pitchTrackerUpdated: true,

      assessmentDate: "",
      assessmentType: "",
      assessmentMode: "",
      assessmentDateTime: "",
      assessmentStatus: "",
      assessmentRemarks: "",

      interviewDate: "",
      interviewDateTime: "",
      interviewer1Name: "",
      interviewer2Name: "",
      interviewStatus: "",
      interviewRemarks: "",

      offerDate: "",
      offerAmount: "",
      joiningDate: "",
      offerStatus: "",
      offerRemarks: "",

      age: 28,
      gender: "Male",
      skills: ["React", "Angular", "Vue.js"],
      preferredCallTime: "11:00 AM - 1:00 PM",
      callOption: "Phone",
      dateApplied: "2025-11-08",
    },
    {
      id: "CAND004",
      mrfId: "MRF101",
      name: "Priya Singh",
      email: "priya.singh@gmail.com",
      contactNumber: "+91-9876543213",
      experience: 3,
      expectedSalary: 10,
      currentSalary: 7.5,
      noticePeriod: "30 days",
      designation: "UI Developer",
      qualification: "B.Tech in IT",
      languages: ["English", "Hindi", "Punjabi"],
      source: "LinkedIn",

      status: "Interview",
      appliedDate: "2025-11-11",
      createdAt: "2025-11-11",
      pitchCallCompleted: true,
      assessmentCompleted: true,
      interviewCompleted: false,
      offerSent: false,

      inviteStatus: "Interested",
      sentToHiringManager: true,
      hmReviewStatus: "Approved",
      currentStage: 3,
      shortlisted: true,
      remark: "Excellent portfolio, strong technical skills",
      isActive: true,

      pitchCallStatus: "Completed",
      pitchCallRemarks: "Very impressed with portfolio and experience",
      pitchCallDate: "2025-11-12",
      pitchCallTime: "15:00",
      pitchTrackerUpdated: true,

      assessmentDate: "2025-11-14",
      assessmentType: "Technical + Design",
      assessmentMode: "Online",
      assessmentDateTime: "2025-11-14T14:00",
      assessmentStatus: "Passed",
      assessmentRemarks: "Scored 85/100. Strong problem-solving skills.",

      interviewDate: "2025-11-19",
      interviewDateTime: "2025-11-19T10:30",
      interviewer1Name: "Sonia Sharma",
      interviewer2Name: "Tech Lead",
      interviewStatus: "Scheduled",
      interviewRemarks: "",

      offerDate: "",
      offerAmount: "",
      joiningDate: "",
      offerStatus: "",
      offerRemarks: "",

      age: 27,
      gender: "Female",
      skills: ["React", "Figma", "CSS", "JavaScript"],
      preferredCallTime: "3:00 PM - 5:00 PM",
      callOption: "Video",
      dateApplied: "2025-11-11",
    },
    {
      id: "CAND005",
      mrfId: "MRF101",
      name: "Amit Patel",
      email: "amit.patel@gmail.com",
      contactNumber: "+91-9876543214",
      experience: 5,
      expectedSalary: 12,
      currentSalary: 9,
      noticePeriod: "Immediate",
      designation: "Senior Frontend Developer",
      qualification: "B.Tech in Computer Science",
      languages: ["English", "Hindi", "Gujarati"],
      source: "Referral",

      status: "Hired",
      appliedDate: "2025-11-05",
      createdAt: "2025-11-05",
      pitchCallCompleted: true,
      assessmentCompleted: true,
      interviewCompleted: true,
      offerSent: true,

      inviteStatus: "Interested",
      sentToHiringManager: true,
      hmReviewStatus: "Approved",
      currentStage: 4,
      shortlisted: true,
      remark: "Perfect fit! Strong referral from senior engineer.",
      isActive: true,

      pitchCallStatus: "Completed",
      pitchCallRemarks: "Excellent candidate with strong background",
      pitchCallDate: "2025-11-06",
      pitchCallTime: "10:00",
      pitchTrackerUpdated: true,

      assessmentDate: "2025-11-08",
      assessmentType: "Technical",
      assessmentMode: "Online",
      assessmentDateTime: "2025-11-08T11:00",
      assessmentStatus: "Passed",
      assessmentRemarks: "Outstanding performance - 95/100",

      interviewDate: "2025-11-10",
      interviewDateTime: "2025-11-10T14:00",
      interviewer1Name: "Sonia Sharma",
      interviewer2Name: "CTO",
      interviewStatus: "Selected",
      interviewRemarks: "Highly recommended by interview panel",

      offerDate: "2025-11-13",
      offerAmount: "12",
      joiningDate: "2025-11-25",
      offerStatus: "Accepted",
      offerRemarks: "Offer accepted, background verification in progress",

      age: 29,
      gender: "Male",
      skills: ["React", "TypeScript", "Next.js", "GraphQL"],
      preferredCallTime: "10:00 AM - 12:00 PM",
      callOption: "Video",
      dateApplied: "2025-11-05",
    },

    // ========== Candidates for MRF102 - Backend Developer ==========
    {
      id: "CAND006",
      mrfId: "MRF102",
      name: "Sana Khan",
      email: "sana.khan@gmail.com",
      contactNumber: "+91-9876543215",
      experience: 5,
      expectedSalary: 12,
      currentSalary: 9.5,
      noticePeriod: "30 days",
      designation: "Backend Engineer",
      qualification: "B.Tech in IT",
      languages: ["English", "Hindi"],
      source: "LinkedIn",

      status: "Interview",
      appliedDate: "2025-11-09",
      createdAt: "2025-11-09",
      pitchCallCompleted: true,
      assessmentCompleted: true,
      interviewCompleted: false,
      offerSent: false,

      inviteStatus: "Interested",
      sentToHiringManager: true,
      hmReviewStatus: "Approved",
      currentStage: 3,
      shortlisted: true,
      remark: "Strong Node.js and MongoDB experience",
      isActive: true,

      pitchCallStatus: "Completed",
      pitchCallRemarks: "Solid technical background, good fit for team",
      pitchCallDate: "2025-11-10",
      pitchCallTime: "11:00",
      pitchTrackerUpdated: true,

      assessmentDate: "2025-11-13",
      assessmentType: "Coding Challenge",
      assessmentMode: "Online",
      assessmentDateTime: "2025-11-13T15:00",
      assessmentStatus: "Passed",
      assessmentRemarks: "Completed challenge successfully",

      interviewDate: "2025-11-17",
      interviewDateTime: "2025-11-17T10:00",
      interviewer1Name: "Sonia Sharma",
      interviewer2Name: "",
      interviewStatus: "Scheduled",
      interviewRemarks: "",

      offerDate: "",
      offerAmount: "",
      joiningDate: "",
      offerStatus: "",
      offerRemarks: "",

      age: 28,
      gender: "Female",
      skills: ["Node.js", "MongoDB", "Express", "AWS"],
      preferredCallTime: "11:00 AM - 1:00 PM",
      callOption: "Video",
      dateApplied: "2025-11-09",
    },
    {
      id: "CAND007",
      mrfId: "MRF102",
      name: "Vikram Patel",
      email: "vikram.patel@gmail.com",
      contactNumber: "+91-9876543216",
      experience: 4,
      expectedSalary: 10,
      currentSalary: 7.5,
      noticePeriod: "20 days",
      designation: "Node.js Developer",
      qualification: "B.Sc. in Computer Science",
      languages: ["English", "Gujarati"],
      source: "Indeed",

      status: "Assessment",
      appliedDate: "2025-11-13",
      createdAt: "2025-11-13",
      pitchCallCompleted: true,
      assessmentCompleted: false,
      interviewCompleted: false,
      offerSent: false,

      inviteStatus: "Interested",
      sentToHiringManager: false,
      hmReviewStatus: "Pending",
      currentStage: 2,
      shortlisted: true,
      remark: "Good technical knowledge, needs assessment",
      isActive: true,

      pitchCallStatus: "Completed",
      pitchCallRemarks: "Candidate is eager to join, has relevant experience",
      pitchCallDate: "2025-11-14",
      pitchCallTime: "16:00",
      pitchTrackerUpdated: true,

      assessmentDate: "2025-11-20",
      assessmentType: "Technical",
      assessmentMode: "Online",
      assessmentDateTime: "2025-11-20T11:00",
      assessmentStatus: "Scheduled",
      assessmentRemarks: "",

      interviewDate: "",
      interviewDateTime: "",
      interviewer1Name: "",
      interviewer2Name: "",
      interviewStatus: "",
      interviewRemarks: "",

      offerDate: "",
      offerAmount: "",
      joiningDate: "",
      offerStatus: "",
      offerRemarks: "",

      age: 26,
      gender: "Male",
      skills: ["Node.js", "Express", "PostgreSQL", "Docker"],
      preferredCallTime: "4:00 PM - 6:00 PM",
      callOption: "Phone",
      dateApplied: "2025-11-13",
    },
    {
      id: "CAND008",
      mrfId: "MRF102",
      name: "Divya Reddy",
      email: "divya.reddy@gmail.com",
      contactNumber: "+91-9876543217",
      experience: 3,
      expectedSalary: 9,
      currentSalary: 6.5,
      noticePeriod: "45 days",
      designation: "Backend Developer",
      qualification: "MCA",
      languages: ["English", "Telugu", "Hindi"],
      source: "Naukri",

      status: "Pitch Call",
      appliedDate: "2025-11-15",
      createdAt: "2025-11-15",
      pitchCallCompleted: false,
      assessmentCompleted: false,
      interviewCompleted: false,
      offerSent: false,

      inviteStatus: "Interested",
      sentToHiringManager: false,
      hmReviewStatus: "Pending",
      currentStage: 1,
      shortlisted: false,
      remark: "Resume looks promising",
      isActive: true,

      pitchCallStatus: "Scheduled",
      pitchCallRemarks: "",
      pitchCallDate: "2025-11-16",
      pitchCallTime: "14:30",
      pitchTrackerUpdated: false,

      assessmentDate: "",
      assessmentType: "",
      assessmentMode: "",
      assessmentDateTime: "",
      assessmentStatus: "",
      assessmentRemarks: "",

      interviewDate: "",
      interviewDateTime: "",
      interviewer1Name: "",
      interviewer2Name: "",
      interviewStatus: "",
      interviewRemarks: "",

      offerDate: "",
      offerAmount: "",
      joiningDate: "",
      offerStatus: "",
      offerRemarks: "",

      age: 25,
      gender: "Female",
      skills: ["Node.js", "MongoDB", "REST APIs"],
      preferredCallTime: "2:30 PM - 4:30 PM",
      callOption: "Video",
      dateApplied: "2025-11-15",
    },

    // ========== Candidates for MRF103 - DevOps Engineer ==========
    {
      id: "CAND009",
      mrfId: "MRF103",
      name: "Arjun Desai",
      email: "arjun.desai@gmail.com",
      contactNumber: "+91-9876543218",
      experience: 6,
      expectedSalary: 18,
      currentSalary: 14,
      noticePeriod: "60 days",
      designation: "Senior DevOps Engineer",
      qualification: "B.Tech in Computer Science",
      languages: ["English", "Hindi", "Marathi"],
      source: "LinkedIn",

      status: "Offer",
      appliedDate: "2025-11-07",
      createdAt: "2025-11-07",
      pitchCallCompleted: true,
      assessmentCompleted: true,
      interviewCompleted: true,
      offerSent: true,

      inviteStatus: "Interested",
      sentToHiringManager: true,
      hmReviewStatus: "Approved",
      currentStage: 4,
      shortlisted: true,
      remark: "Exceptional DevOps skills, AWS certified",
      isActive: true,

      pitchCallStatus: "Completed",
      pitchCallRemarks: "Very experienced, strong AWS background",
      pitchCallDate: "2025-11-08",
      pitchCallTime: "10:00",
      pitchTrackerUpdated: true,

      assessmentDate: "2025-11-11",
      assessmentType: "Practical DevOps Challenge",
      assessmentMode: "Online",
      assessmentDateTime: "2025-11-11T09:00",
      assessmentStatus: "Passed",
      assessmentRemarks: "Excellent practical knowledge - 90/100",

      interviewDate: "2025-11-13",
      interviewDateTime: "2025-11-13T15:00",
      interviewer1Name: "Sarah Johnson",
      interviewer2Name: "DevOps Lead",
      interviewStatus: "Selected",
      interviewRemarks: "Strong candidate, recommended for hire",

      offerDate: "2025-11-14",
      offerAmount: "18",
      joiningDate: "2026-01-15",
      offerStatus: "Sent",
      offerRemarks: "Waiting for candidate response",

      age: 30,
      gender: "Male",
      skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Jenkins"],
      preferredCallTime: "10:00 AM - 12:00 PM",
      callOption: "Video",
      dateApplied: "2025-11-07",
    },
    {
      id: "CAND010",
      mrfId: "MRF103",
      name: "Neha Gupta",
      email: "neha.gupta@gmail.com",
      contactNumber: "+91-9876543219",
      experience: 4,
      expectedSalary: 14,
      currentSalary: 10,
      noticePeriod: "30 days",
      designation: "DevOps Engineer",
      qualification: "B.Tech in IT",
      languages: ["English", "Hindi"],
      source: "Naukri",

      status: "Pitch Call",
      appliedDate: "2025-11-14",
      createdAt: "2025-11-14",
      pitchCallCompleted: false,
      assessmentCompleted: false,
      interviewCompleted: false,
      offerSent: false,

      inviteStatus: "Interested",
      sentToHiringManager: false,
      hmReviewStatus: "Pending",
      currentStage: 1,
      shortlisted: false,
      remark: "Good CI/CD experience",
      isActive: true,

      pitchCallStatus: "Pending",
      pitchCallRemarks: "",
      pitchCallDate: "",
      pitchCallTime: "",
      pitchTrackerUpdated: false,

      assessmentDate: "",
      assessmentType: "",
      assessmentMode: "",
      assessmentDateTime: "",
      assessmentStatus: "",
      assessmentRemarks: "",

      interviewDate: "",
      interviewDateTime: "",
      interviewer1Name: "",
      interviewer2Name: "",
      interviewStatus: "",
      interviewRemarks: "",

      offerDate: "",
      offerAmount: "",
      joiningDate: "",
      offerStatus: "",
      offerRemarks: "",

      age: 27,
      gender: "Female",
      skills: ["AWS", "Jenkins", "Docker", "Linux"],
      preferredCallTime: "11:00 AM - 1:00 PM",
      callOption: "Phone",
      dateApplied: "2025-11-14",
    },

    // ========== Candidates for MRF104 - Product Manager ==========
    {
      id: "CAND011",
      mrfId: "MRF104",
      name: "Karthik Iyer",
      email: "karthik.iyer@gmail.com",
      contactNumber: "+91-9876543220",
      experience: 7,
      expectedSalary: 25,
      currentSalary: 20,
      noticePeriod: "90 days",
      designation: "Senior Product Manager",
      qualification: "MBA + B.Tech",
      languages: ["English", "Hindi", "Tamil"],
      source: "LinkedIn",

      status: "Assessment",
      appliedDate: "2025-11-06",
      createdAt: "2025-11-06",
      pitchCallCompleted: true,
      assessmentCompleted: false,
      interviewCompleted: false,
      offerSent: false,

      inviteStatus: "Interested",
      sentToHiringManager: false,
      hmReviewStatus: "Pending",
      currentStage: 2,
      shortlisted: true,
      remark: "Impressive product management background",
      isActive: true,

      pitchCallStatus: "Completed",
      pitchCallRemarks: "Very strategic thinker, excellent communication",
      pitchCallDate: "2025-11-07",
      pitchCallTime: "16:00",
      pitchTrackerUpdated: true,

      assessmentDate: "2025-11-18",
      assessmentType: "Product Case Study",
      assessmentMode: "In-Person",
      assessmentDateTime: "2025-11-18T14:00",
      assessmentStatus: "Scheduled",
      assessmentRemarks: "",

      interviewDate: "",
      interviewDateTime: "",
      interviewer1Name: "",
      interviewer2Name: "",
      interviewStatus: "",
      interviewRemarks: "",

      offerDate: "",
      offerAmount: "",
      joiningDate: "",
      offerStatus: "",
      offerRemarks: "",

      age: 32,
      gender: "Male",
      skills: ["Product Strategy", "Roadmap Planning", "User Research", "Analytics"],
      preferredCallTime: "4:00 PM - 6:00 PM",
      callOption: "Video",
      dateApplied: "2025-11-06",
    },
  ]);

  // ✅ Application state
  const [state, setState] = useState({
    currentUserId: "EMP002",  // Must match assignedTo in MRFs
    selectedMrfId: null,
  });

  // ✅ Update state function (used by ManageMrf for rounds and navigation)
  const updateState = (updates) => {
    setState((prev) => ({ ...prev, ...updates }));

    // If mockMrfs is in the updates, also update the mockMrfs state
    if (updates.mockMrfs) {
      setMockMrfs(updates.mockMrfs);
    }
  };

  // ✅ Update candidate function (used by all three pages)
  const updateCandidate = (candidateId, updatedData) => {
    setMockCandidates((prev) =>
      prev.map((c) =>
        c.id === candidateId ? { ...c, ...updatedData } : c
      )
    );
  };

  // ✅ Update user function (for role switching)
  const updateUser = (updatedUser) => {
    setCurrentUserRole(updatedUser.role);
  };

  // ✅ Provide all required values
  const value = {
    mockCandidates,
    mockMrfs,
    mockEmployees,
    updateCandidate,
    updateUser,
    state,
    updateState,
    currentUser,
    setMockCandidates,  // ✅ For adding new candidates
    setMockMrfs,        // ✅ For updating MRFs
  };

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
};

export const useAppContext = () => useContext(AppContext);